language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - yarn install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

deploy:
  - provider: script
    script: chmod +x ./node_modules/@boldgrid/wordpress-tag-sync/release.sh && ./node_modules/@boldgrid/wordpress-tag-sync/release.sh
    skip_cleanup: true
    on:
      tags: true
      php: '5.6'
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "post-and-page-builder.zip"
    skip_cleanup: true
    on:
      tags: true
      php: '5.6'
